name: CI/CD
on: 
  push:
    branches: 
      - master
jobs: 
  build:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code actions/checkout@v2
      uses: actions/checkout@v2
      
    - name: Start Scan
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://blacklock.io/api/scans/${{ secrets.SCAN_ID }}/start/" 
        method: "POST"
        customHeaders: '{ "Api-Key": "${{ secrets.BLACKLOCK_API_KEY }}" }'
      env:
        SCAN_ID: ${{ secrets.SCAN_ID }}
